version: '2.3'
services:
  weblate:
    build: .
    image: weblate-aurestic
    networks:
      - proxy-network
      - postgres-network
      - redis-network
    tmpfs:
      - /app/cache
    volumes:
      - ./data/weblate:/app/data
    env_file:
      - ./environment
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:${WEBLATE_SITE_DOMAIN:-weblate.aurestic.com}
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=proxy-network

networks:
  proxy-network:
    external: true
  postgres-network:
    external: true
  redis-network:
    external: true
